/*

In cpp src file we just have text a bunch of text to convert this c++ code language text into actual application 
there are two imp steps in cpp -
1. Compilation 
2. Linking

In this document we will learn cpp compilation process in much depth / for more depth revision refer 
The cherno's cpp series how compiler works video.

1. We have bunch of cpp files , this files just contains the text cpp code.

2. This individual cpp file are called as translation units for each trasalation unit
a obj file is generated by our compiler.

3. There is no significance of folder and file structure in cpp, we just need a way to give source code
to compiler and let him know which type of file it is .cpp tells that it is a cpp file.

4. we can also gives the compiler .yogesh file wiith cpp src code and tells him that it contains cpp source
code then also it will works fine.

5. Now lets again comes to compilation , the first step is preprocessing.

There are 4 imp preprocessor statements , there can be more but not so useful - 
1 #include -> copy paste the code of header files in source fie
2 #define -> give alias to any identifier or ....
3 #if -> we can give condition to the compiler whether the below code has to be executed or not
4. #endif -> just ends the #if directive.

You can see each examples in visual studio.



*/